/* Mount the REAL CartMoment against a COMPOSED cart. See composed.html for why.
 *
 * THIS IS THE INPUT THE PRODUCT ACTUALLY PRODUCES, and that is the whole point of it
 * existing alongside cartHarness.jsx. That fixture is twelve bare nouns — "Blueberries",
 * "Eggs", "Olive oil" — carrying no `why`, because it was modelled on the Phase 2 mock,
 * which was hand-authored HTML built from the same bare nouns the Phase 1 probe invented.
 * Nothing in that chain ever held a `why`, so the double-prose row could not be seen by
 * the mock, by the probe, or by the test that measured the build.
 *
 * A composed row is different in three ways that all matter: the name is an authored PICK
 * name ("Frozen broccoli or green beans"), every row carries a `why`, and some rows carry
 * an authored `perimeterId`. The fixture below is generated by running the SHIPPING
 * attachCards over the SHIPPING PICKS — listMatch reaches the KB through node:fs and
 * cannot be bundled for a browser, so the same split the loop test uses applies:
 * semantics proven in node by listMatch.test.js, geometry proven here.
 */

import { createRoot } from 'react-dom/client';
import { useState } from 'react';
import CartMoment from '../src/components/CartMoment.jsx';
import { cartProgress } from '../src/lib/cart.js';
import FIXTURE from './composedFixture.json';
import '../src/index.css';

const ITEMS = FIXTURE;

function Harness() {
  const [list, setList] = useState({ goal: null, intro: '', items: ITEMS });
  const mutate = (fn) => setList((cur) => fn(cur));

  const cart = {
    list,
    hasCart: true,
    loading: false,
    progress: cartProgress(list),
    toggle: (id) =>
      mutate((c) => ({ ...c, items: c.items.map((i) => (i.id === id ? { ...i, checked: !i.checked } : i)) })),
    remove: (id) => mutate((c) => ({ ...c, items: c.items.filter((i) => i.id !== id) })),
    add: (name) =>
      mutate((c) => ({
        ...c,
        items: [...c.items, { id: `n${c.items.length}`, name, category: 'Added', checked: false, source: 'user' }],
      })),
    keep: () => {},
    takeOffer: () => {},
    compose: async () => {},
    startNewTrip: () => mutate(() => ({ goal: null, intro: '', items: [] })),
  };

  return <CartMoment cart={cart} goals={[]} goal={null} />;
}

createRoot(document.getElementById('root')).render(<Harness />);
