// Mount point for test/needsFix.mjs. The harness module it renders is GENERATED by that
// script on each run, so the seed row shapes live beside the assertions that read them.
import { createRoot } from 'react-dom/client';
import Harness from './needsFixHarness.jsx';
import '../src/index.css';

createRoot(document.getElementById('root')).render(<Harness />);
