-- subscriptions.status / subscriptions.provider — the CHECK constraints.
--
-- ⚠️ 2026-08-16 — READ THIS BLOCK BEFORE THE ONE UNDER IT. STEP 1 IS **HALF APPLIED**, AND
-- THE LIVE TABLE IS NOW IN A STATE NEITHER THIS FILE NOR schema.sql DESCRIBES.
--
-- Third live reading, same script, unpiped, exit 0:
--
--     cd server && node --use-system-ca scripts/subscriptionConstraints.livetest.js
--
--   status    live accepts  trialing, active, past_due, canceled, expired   ← matches schema.sql
--   provider  live accepts  stripe, apple, promo, revenuecat               ← A SUPERSET OF BOTH
--   control   REJECTED on both columns  ← so these are WIDE constraints, not dropped ones
--
-- ✅ **THE BLOCKING HALF IS CLEARED.** `'apple'` is accepted, so `routes/revenuecat.js:98`
-- writes, the handler no longer 500s, and INITIAL_PURCHASE lands. The shopper who has just
-- paid gets their row.
--
-- ⚠️ **THE SECOND HALF OF STEP 1 IS NOT APPLIED: `'revenuecat'` IS STILL ACCEPTED.** So the
-- live vocabulary is `stripe, apple, promo, revenuecat` — wider than schema.sql declares
-- (which omits `revenuecat`) and wider than step 1 intends (which drops it). **Whatever was
-- run added `'apple'` without removing `'revenuecat'`; it was not this file's step 1.**
--
-- ⚠️ **DO NOT RE-RUN STEP 1 ON THAT READING ALONE.** It drops every provider CHECK and rebuilds
-- one, which is correct DDL for this state and is still DDL against a live table carrying real
-- constraints — separately proposed, separately approved work. The urgency is gone with the
-- blocking half: `'revenuecat'` is a permitted value that **nothing writes**, so it costs no
-- webhook and no shopper today. It is a slot, and this file's own argument is about what fills
-- a slot later.
--
-- ⚠️ **THE CONTROL LINE IS WHY THE ABOVE IS WORTH ANYTHING.** An accept-only probe cannot tell
-- a WIDE constraint from NO constraint, and would print its most reassuring output in exactly
-- the case where the column has lost its guard. The control was offered and rejected on both
-- columns, so a CHECK is live and enforcing on each.
--
-- 📋 **THE LESSON, AND THIS ENTRY HAS NOW BEEN WRONG IN BOTH DIRECTIONS.** It read "no-op, do
-- not run" (wrong), then "still broken, someone reported it fixed" (right at the time), and now
-- "half applied". **Every one of those was settled by running the script and none by reading a
-- file.** ⚠️ **And the trap has only changed sides:** *"provider accepts revenuecat"* was the
-- misleading half of the fixed-sounding sentence before, and it is still true now — it is
-- simply no longer the interesting line. **Read `apple`, then read `revenuecat`, and read both.**
--
-- The status half never reproduced: `'expired'` is accepted and always was. Account:
-- `docs/SCHEMA-AUDIT.md`.
--
-- ─────────────────────────────────────────────────────────────────────────────────────────
-- The original audit follows, unedited. Its code enumeration is still accurate and is why the
-- reconciliation keeps `'apple'` rather than teaching the route to write `'revenuecat'`.
--
-- ⚠️ READ THIS BEFORE RUNNING IT. THE PREMISE DID NOT REPRODUCE.
--
-- This file was written to widen `SUBSCRIPTION_STATUSES` and add a `'revenuecat'` provider.
-- Auditing the code first — which is the order this repo insists on — found that **every
-- value the server can write is already permitted by the constraints declared in
-- `schema.sql`**, and that the `'revenuecat'` half would make things worse rather than
-- better. Both findings are written out below with the evidence, because a migration that
-- turns out to be a no-op should say so rather than be run and forgotten.
--
-- ═══ WHAT schema.sql DECLARES (lines 168–171) ═══════════════════════════════════════════
--
--   status   text not null default 'trialing'
--     check (status in ('trialing', 'active', 'past_due', 'canceled', 'expired'))
--   provider text not null default 'promo'
--     check (provider in ('stripe', 'apple', 'promo'))
--
-- ═══ EVERY WRITER, ENUMERATED ═══════════════════════════════════════════════════════════
--
-- status, from the three things that write one:
--   lib/subscription.js:110   ensureTrial          → 'trialing'                    ✅ allowed
--   lib/subscription.js:126   mapStripeStatus      → trialing | active | past_due
--                                                    | canceled | expired          ✅ allowed
--   routes/revenuecat.js:39   mapRevenueCatStatus  → trialing | active | past_due
--                                                    | expired                     ✅ allowed
--   routes/stripe.js:100                           → 'past_due'                    ✅ allowed
--
-- provider, from the three things that write one:
--   lib/subscription.js:111   ensureTrial          → 'promo'                       ✅ allowed
--   routes/stripe.js:52,80,101                     → 'stripe'                      ✅ allowed
--   routes/revenuecat.js:98                        → 'apple'                       ✅ allowed
--
-- **`'trialing'` is already permitted**, so the trial path is not blocked by a constraint.
-- `mapRevenueCatStatus` returns it for any event whose `period_type` is `TRIAL` — which for a
-- trial subscriber is INITIAL_PURCHASE, CANCELLATION (still inside the window) and, on the
-- paying side later, RENEWAL. The upsert those produce satisfies the CHECK as written.
--
-- ⚠️ **NOTHING WRITES `'revenuecat'`, AND ADDING IT IS ACTIVELY HARMFUL.** The webhook writes
-- `provider: 'apple'` (routes/revenuecat.js:98) — deliberately, because the *store* is Apple
-- and RevenueCat is the pipe. Adding `'revenuecat'` to the CHECK creates a permitted value
-- that no code path writes, and the iOS client has a switch on this exact column:
--
--   SubscriptionSnapshot.Provider.init(raw:)  — stripe | apple | promo | unrecognized(String)
--   SubscriptionSnapshot.hasManagedBilling    — true for .stripe and .apple, FALSE for
--                                               .unrecognized
--   MembershipRow.controlTitle                — "Manage" only when hasManagedBilling
--
-- So a row written as `'revenuecat'` decodes to `.unrecognized("revenuecat")`, which reports
-- **no managed billing**, and a real paying subscriber is offered **"See plans"** instead of
-- **"Manage"** — a door to their own billing page, missing, for the only shoppers who have
-- given us money. It fails silently and in the expensive direction.
--
-- It is also, precisely, the defect that was named as the reason for having ONE RevenueCat
-- key field: *a slot with nothing to put in it is a slot somebody later fills wrongly.*
--
-- ═══ WHAT THIS FILE COULD NOT VERIFY, AND HOW TO SETTLE IT IN ONE QUERY ═════════════════
--
-- ⚠️ The audit above is of the CODE and of `schema.sql`. **It is not a reading of the live
-- constraint.** `docs/SCHEMA-AUDIT.md` compares COLUMNS and says so explicitly — its method
-- does not read constraints or indexes — so "schema.sql says X" is not evidence that the live
-- table says X. This repo has already been bitten by exactly that gap (`push_tokens` recorded
-- as applied and absent; `counter_cards.aliases` missing from both).
--
-- **Run this first. It is read-only and it settles the whole question:**
--
--   select conname, pg_get_constraintdef(oid)
--   from pg_constraint
--   where conrelid = 'public.subscriptions'::regclass and contype = 'c';
--
-- If the two definitions it prints match the two in `schema.sql` above, **this file is a
-- no-op and should not be run.** If they do not, the statements below reconcile the live
-- table to the declared contract — and the difference is itself a finding worth recording in
-- `docs/SCHEMA-AUDIT.md`, because it would mean the live schema drifted from the migration.
--
-- ═══ THE RECONCILIATION, IF THE QUERY SHOWS A GAP ══════════════════════════════════════
--
-- Idempotent, DDL only, no data write — `schemaSafety.test.js` fails on any
-- insert/update/delete/truncate in a `supabase/*.sql` file outside a function body, and
-- applying a schema must never change what a user has.
--
-- ⚠️ `'revenuecat'` IS DELIBERATELY ABSENT FROM THE PROVIDER LIST BELOW. See above. If it is
-- ever genuinely needed, the client's `Provider` enum and `hasManagedBilling` must gain the
-- case **in the same change**, or a paying member loses the door to their billing page.

-- ═══ STEP 0 — PRE-FLIGHT, READ-ONLY. RUN THIS FIRST AND READ BOTH ANSWERS ═══════════════
--
-- ⚠️ ADDING A CHECK VALIDATES EVERY EXISTING ROW, so a single row holding a value the new
-- list omits makes the ALTER fail. The table held 0 rows on 2026-08-13; that is a stale
-- measurement and this is the query that refreshes it. A row reading `provider='revenuecat'`
-- would have to be corrected before the provider statement can run.
--
--   select conname, pg_get_constraintdef(oid) as def
--   from pg_constraint
--   where conrelid = 'public.subscriptions'::regclass and contype = 'c';
--
--   select provider, status, count(*) from public.subscriptions group by 1, 2 order by 3 desc;

-- ═══ STEP 1 — THE PROVIDER HALF. THIS IS THE ONE THAT NEEDS RUNNING ═════════════════════
--
-- ⚠️ **RUN THE PROVIDER BLOCK ONLY. THE STATUS BLOCK IS A MEASURED NO-OP AND IS KEPT BELOW
-- FOR THE CASE WHERE STEP 0 SAYS OTHERWISE.** Both live constraints were read behaviourally
-- on 2026-08-16 (`scripts/subscriptionConstraints.livetest.js`): `status` accepts exactly the
-- five values `schema.sql` declares, and re-running its DDL would drop and re-add an identical
-- constraint — an ACCESS EXCLUSIVE lock and a full revalidation, bought for nothing. Touching
-- a constraint that is already correct is not free and is not more careful.
--
-- ⚠️ **THE LOOP IS NOT A STYLE CHOICE — `limit 1` WAS WRONG HERE.** This file previously
-- dropped ONE matching constraint. If a hand-written migration ever left two constraints on
-- the column, dropping one leaves the other enforcing, the accepted set becomes their
-- INTERSECTION, and `add constraint` then fails on a duplicate name — a half-applied state
-- whose symptom is identical to not having run it. Drop every match, then declare one list.
-- (Measured today: there is exactly one provider constraint, so `limit 1` would have worked.
-- It is the state this could not see that the loop is for.)

do $$
declare c record;
begin
  for c in
    select conname from pg_constraint
    where conrelid = 'public.subscriptions'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%provider%'
  loop
    execute format('alter table public.subscriptions drop constraint %I', c.conname);
  end loop;

  -- The list is every value a writer in this repo can produce, enumerated from the code
  -- rather than from the integration's name:
  --   'promo'   lib/subscription.js:111   ensureTrial
  --   'stripe'  routes/stripe.js:52, 80, 101
  --   'apple'   routes/revenuecat.js:98   — ONE call site, an unconditional literal, so it is
  --                                         what EVERY RevenueCat event type writes
  alter table public.subscriptions
    add constraint subscriptions_provider_check
    check (provider in ('stripe', 'apple', 'promo'));
end $$;

-- ═══ STEP 2 — PROVE IT, AND THE LINE TO READ ═══════════════════════════════════════════
--
--   cd server && node --use-system-ca scripts/subscriptionConstraints.livetest.js
--
--   provider 'apple' accepted:      YES   ← fixed
--   provider 'revenuecat' accepted: NO    ← the writerless slot is closed
--
-- ⚠️ **BOTH LINES, NOT THE FIRST ONE.** "provider accepts revenuecat" is a true sentence about
-- the BROKEN table as well as a wrong one about the fixed table, and reading it as success is
-- the recorded way this blocker gets ticked off while every webhook write still 500s.

-- ═══ THE STATUS HALF — KEPT, NOT FOR RUNNING. See step 1. ══════════════════════════════
--
-- do $$
-- declare c record;
-- begin
--   for c in
--     select conname from pg_constraint
--     where conrelid = 'public.subscriptions'::regclass
--       and contype = 'c'
--       and pg_get_constraintdef(oid) like '%status%'
--   loop
--     execute format('alter table public.subscriptions drop constraint %I', c.conname);
--   end loop;
--
--   alter table public.subscriptions
--     add constraint subscriptions_status_check
--     check (status in ('trialing', 'active', 'past_due', 'canceled', 'expired'));
-- end $$;
