import { colors, fonts, kristyVoice, radii } from '../lib/tokens.js';
import { GoldThread } from './GoldThread.jsx';
import CounterCard from './CounterCard.jsx';

/* ═══════════════ What an asked question renders ═══════════════

   Four outcomes, one component, and the shopper is never told which machinery produced
   their answer:

     CARD            curated, retrieved, or generated — the SAME component either way.
     OUT OF SCOPE    one line in her voice. Not an error, not a form validation.
     NEAREST         the corpus had nothing for this, so the closest card is offered
                     honestly as the closest card, never as the answer to what was asked.
     GATED           the free card stands; the personalized read is the member part.

   A GENERATED CARD CARRIES NO AI STYLING, no "generated by" badge, no disclaimer chrome,
   no different border. That is deliberate and it is the whole bet: either a generated card
   clears the same bar a curated one does — the same lint, the same claim lock, the same
   tier system — or it does not ship. A badge saying "this one is machine-written" would be
   an admission that the bar is lower, and it would teach shoppers to discount exactly the
   answers the corpus is growing from. */

export default function CounterAnswer({ resp, onUpgrade, onAddToCart }) {
  if (!resp) return null;

  // Out of scope, or over the read ceiling. One line, in voice, no error state and no
  // explanation of the rule that produced it.
  if (resp.out_of_scope || resp.rateLimited) {
    return (
      <div style={styles.wrap} data-counter-answer="line">
        <p style={{ ...kristyVoice, ...styles.line }}>{resp.line}</p>
      </div>
    );
  }

  // Nothing in the corpus, and nothing near it either.
  if (!resp.card) {
    return (
      <div style={styles.wrap} data-counter-answer="miss">
        <p style={{ ...kristyVoice, ...styles.line }}>{resp.line || 'No solid read on that one yet.'}</p>
      </div>
    );
  }

  // The corpus could not answer THIS question, so the nearest card is offered as what it
  // is. Said before the card, not after: a shopper who reads the card first and the caveat
  // second has already taken it as the answer.
  const nearest = resp.nearest === true;

  return (
    <div style={styles.wrap} data-counter-answer={nearest ? 'nearest' : 'card'}>
      {nearest && (
        <p style={{ ...kristyVoice, ...styles.line }} data-nearest-line>
          {resp.line || 'No solid read on that exact question yet. The closest one:'}
        </p>
      )}

      <CounterCard card={resp.card} onAddToCart={onAddToCart} />

      {/* Kristy's personalized read (premium). */}
      {resp.personal?.answer && (
        <>
          <GoldThread />
          <p style={{ ...kristyVoice, ...styles.personal }}>{resp.personal.answer}</p>
        </>
      )}

      {/* The withheld personalized read. The card above still stands on its own. */}
      {resp.gated && (
        <div style={styles.gate}>
          <GoldThread />
          <p style={{ ...kristyVoice, ...styles.gateLine }}>{resp.upsell}</p>
          {onUpgrade && (
            <button type="button" style={styles.gateCta} onClick={onUpgrade}>
              Unlock the personalized read
            </button>
          )}
        </div>
      )}
    </div>
  );
}

/* ═══════════════ Waiting ═══════════════ */

// A skeleton in the CARD's shape, not a spinner. Generation takes seconds, and a shopper
// who can see the answer's outline forming is waiting for something; a spinner is waiting
// for nothing. The bars mirror eyebrow, headline, do — so the layout does not jump when
// the real card lands.
export function CounterAnswerSkeleton() {
  return (
    <div style={styles.wrap} aria-busy="true" aria-live="polite" data-counter-skeleton>
      <div style={styles.skelCard}>
        <span style={styles.srOnly}>Reading the counter…</span>
        <div style={{ ...styles.bar, width: '38%', height: 10 }} />
        <div style={{ ...styles.bar, width: '92%', height: 19, marginTop: 10 }} />
        <div style={{ ...styles.bar, width: '64%', height: 19, marginTop: 6 }} />
        <div style={{ ...styles.bar, width: '80%', height: 13, marginTop: 12 }} />
        <div style={{ ...styles.bar, width: '46%', height: 13, marginTop: 6 }} />
      </div>
    </div>
  );
}

const styles = {
  wrap: { display: 'flex', flexDirection: 'column', gap: 12 },
  line: { margin: 0, fontSize: 16.5, lineHeight: 1.5, color: colors.textPrimary },
  personal: { margin: 0, fontSize: 17, lineHeight: 1.55, color: colors.textPrimary },
  gate: { display: 'flex', flexDirection: 'column', gap: 10 },
  gateLine: { margin: 0, fontSize: 16, lineHeight: 1.55, color: colors.textPrimary },
  gateCta: {
    alignSelf: 'stretch', padding: '12px 16px', borderRadius: radii.button,
    border: `0.5px solid ${colors.hairline}`, background: 'transparent',
    color: colors.inkBody, fontFamily: fonts.ui, fontWeight: 700, fontSize: 15, cursor: 'pointer',
  },
  skelCard: {
    display: 'flex', flexDirection: 'column', padding: '14px 15px', borderRadius: 14,
    background: colors.surface,
    boxShadow: `inset 0 1px 0 ${colors.edgeHighlight}, ${colors.shadowCard}`,
  },
  bar: {
    borderRadius: 6, background: colors.hairline, opacity: 0.5,
    animation: 'kristyPulse 1.4s ease-in-out infinite',
  },
  srOnly: {
    position: 'absolute', width: 1, height: 1, overflow: 'hidden',
    clip: 'rect(0 0 0 0)', whiteSpace: 'nowrap',
  },
};
