// The shopper's real baseline — what they actually buy, not what they should.
//
// This is the groundwork for the thing that makes "subtle yet effective over weeks"
// real: a list that nudges from where the shopper ACTUALLY is, trip after trip,
// rather than from a blank ideal every time. Most nutrition apps demand a perfect
// cart on every trip and get deleted for it. A list that respects you and improves
// you slowly enough that you never feel managed is the one people keep.
//
// It is deliberately small. The signals already collected are enough to answer three
// questions honestly, and answering them is worth more than a model of the shopper
// that nobody asked for:
//   • STAPLES  — what they keep buying. Checked off, trip after trip. Their real
//                basket, and the thing a nudge should lean FROM.
//   • AVOIDED  — what they took off the list. Never suggested again.
//   • DECLINED — swaps they turned down. Never offered again, and never quietly
//                slipped into the cart as a "nudge" either, which would be the same
//                suggestion wearing a different hat.
//
// No model, no inference, no claim: every value here is a grocery NAME the shopper
// themselves put on or took off a list.

import { canonicalItem } from './list.js';
import { declinedItemNames } from './listVoice.js';

// Seen this many times before it counts as a pattern. Once is a trip; twice is a
// habit. Set low on purpose — the whole point is to be useful early, and the cost of
// a wrong guess here is one item's ordering, not a claim.
const STAPLE_THRESHOLD = 2;

const canonSet = (names) => {
  const s = new Set();
  for (const n of names || []) {
    const c = canonicalItem(n);
    if (c) s.add(c);
  }
  return s;
};

/**
 * Read the shopper's real baseline out of the signals they generated by shopping.
 * @returns {{ staples:string[], avoided:Set<string>, declined:Set<string> }}
 */
export function buildBaseline(signals = {}) {
  // `kept` accumulates a name every time a row is checked off, so the number of
  // occurrences IS the frequency. Repetition is the signal; deduping it would throw
  // away the only evidence of what they actually buy.
  const counts = new Map();
  for (const name of signals.kept || []) {
    const c = canonicalItem(name);
    if (!c) continue;
    const cur = counts.get(c);
    if (cur) cur.n += 1;
    else counts.set(c, { name, n: 1 });
  }

  const staples = [...counts.values()]
    .filter((v) => v.n >= STAPLE_THRESHOLD)
    .sort((a, b) => b.n - a.n)
    .map((v) => v.name)
    .slice(0, 20);

  return {
    staples,
    avoided: canonSet(signals.removed),
    // A declined swap is a preference learned. Suppressing only the note but still
    // adding the item as a "nudge" is the same suggestion wearing a different hat.
    declined: canonSet(declinedItemNames(signals.declinedSwaps)),
  };
}

/**
 * Should this item be kept OUT of a suggestion, given what the shopper has already
 * told us by removing and declining? Grounded entirely in their own past taps.
 */
export function suppressedByBaseline(name, baseline) {
  const c = canonicalItem(name);
  if (!c || !baseline) return false;
  return baseline.avoided.has(c) || baseline.declined.has(c);
}
